# Generated by Django 2.1.5 on 2019-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=40)),
                ('cost_included', models.TextField()),
                ('cost_excluded', models.TextField()),
                ('season', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
